export default [
  {
    name:'张炎',
    img:'./img/1.jpeg'
  },
  {
    name:'杨峰',
    img:'./img/2.jpeg'
  },
  {
    name:'唐小卓',
    img:'./img/3.jpeg'
  },
  {
    name:'朱蔚',
    img:'./img/4.jpeg'
  },
  {
    name:'李利德',
    img:'./img/0.gif'
  },
  {
    name:'李磊',
    img:'./img/WechatIMG59.jpeg'
  },
  {
    name:'李爽',
    img:'./img/WechatIMG60.jpeg'
  },
  {
    name:'李添翼',
    img:'./img/WechatIMG61.jpeg'
  },
  {
    name:'刘源',
    img:'./img/WechatIMG62.jpeg'
  },
  {
    name:'李星谣',
    img:'./img/WechatIMG63.jpeg'
  },
  {
    name:'李义文',
    img:'./img/WechatIMG64.jpeg'
  },
  {
    name:'庞玉彤',
    img:'./img/WechatIMG65.jpeg'
  },
  {
    name:'彭世航',
    img:'./img/WechatIMG66.jpeg'
  },
  {
    name:'钱学敏',
    img:'./img/WechatIMG67.jpeg'
  },
  {
    name:'史鹏飞',
    img:'./img/WechatIMG68.jpeg'
  },
  {
    name:'唐莉',
    img:'./img/WechatIMG69.jpeg'
  },
  {
    name:'王春明',
    img:'./img/WechatIMG70.jpeg'
  },
  {
    name:'夏文海',
    img:'./img/WechatIMG71.jpeg'
  },
  {
    name:'徐辛承',
    img:'./img/WechatIMG72.jpeg'
  },
  {
    name:'岳奎',
    img:'./img/WechatIMG73.jpeg'
  },
  {
    name:'岳贤强',
    img:'./img/WechatIMG74.jpeg'
  },
  {
    name:'张浩宇',
    img:'./img/WechatIMG75.jpeg'
  },
  {
    name:'张凯凯',
    img:'./img/WechatIMG76.jpeg'
  },
  {
    name:'郭转生',
    img:'./img/WechatIMG77.jpeg'
  },
  {
    name:'安瑶',
    img:'./img/WechatIMG78.jpeg'
  },
  {
    name:'安宇鑫',
    img:'./img/WechatIMG79.jpeg'
  },
  {
    name:'白璐',
    img:'./img/WechatIMG80.jpeg'
  },
  {
    name:'常洪强',
    img:'./img/WechatIMG81.jpeg'
  },
  {
    name:'陈元',
    img:'./img/WechatIMG82.jpeg'
  },
  {
    name:'崔征云',
    img:'./img/WechatIMG83.jpeg'
  },
  {
    name:'宫照刚',
    img:'./img/WechatIMG84.jpeg'
  },
  {
    name:'何喻',
    img:'./img/WechatIMG85.jpeg'
  },
  {
    name:'焦帅',
    img:'./img/WechatIMG86.jpeg'
  },
  {
    name:'李方超',
    img:'./img/WechatIMG87.jpeg'
  },
  {
    name:'李宏正',
    img:'./img/WechatIMG88.jpeg'
  },
  {
    name:'刘报童',
    img:'./img/WechatIMG89.jpeg'
  },
  {
    name:'刘力云',
    img:'./img/WechatIMG90.jpeg'
  },
  {
    name:'吕姣',
    img:'./img/WechatIMG91.jpeg'
  },
  {
    name:'秦振海',
    img:'./img/WechatIMG92.jpeg'
  },
  {
    name:'戚仁龙',
    img:'./img/WechatIMG93.jpeg'
  },
  {
    name:'宋慧超',
    img:'./img/WechatIMG94.jpeg'
  },
  {
    name:'田利新',
    img:'./img/WechatIMG95.jpeg'
  },
  {
    name:'王佳琦',
    img:'./img/WechatIMG96.jpeg'
  },
  {
    name:'王凯杰',
    img:'./img/WechatIMG97.jpeg'
  },
  {
    name:'王宁',
    img:'./img/WechatIMG98.jpeg'
  },
  {
    name:'王莎莎',
    img:'./img/WechatIMG99.jpeg'
  },
  {
    name:'韦宗伟',
    img:'./img/WechatIMG100.jpeg'
  },
  {
    name:'肖德超',
    img:'./img/WechatIMG101.jpeg'
  },
  {
    name:'徐泽锋',
    img:'./img/WechatIMG103.jpeg'
  },
  {
    name:'杨元',
    img:'./img/WechatIMG104.jpeg'
  },
  {
    name:'闫兴茂',
    img:'./img/WechatIMG105.jpeg'
  },
  {
    name:'张建国',
    img:'./img/WechatIMG106.jpeg'
  },
  {
    name:'张琦',
    img:'./img/WechatIMG107.jpeg'
  },
  {
    name:'张文姗',
    img:'./img/WechatIMG108.jpeg'
  },
  {
    name:'赵宏斌',
    img:'./img/WechatIMG109.jpeg'
  },
  {
    name:'赵敏',
    img:'./img/WechatIMG110.jpeg'
  }
]